
modLoader="javafml"
loaderVersion="[31,)"

issueTrackerURL="https://github.com/hds536jhmk/Yarcot/issues"

[[mods]]

modId="yarcot"
version="1.15.2-0.0.4"
displayName="Yarcot"

# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/hds536jhmk/Yarcot"

logoFile="yarcot.png"

credits="Psyco_Manu"
authors="hds536jhmk"

description='''
Yet Another Random Collection of Things
'''

[[dependencies.yarcot]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.yarcot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
